version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/app.db
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - JOBS_ENABLED=true
      - JOBS_SCRAPER_INTERVAL=45
      - JOBS_SCRAPER_INITIAL_DELAY=5
      - JOBS_HEALTH_CHECK_INTERVAL=5
      - JOBS_CLEANUP_CRON=0 2 * * *
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s